### ISSUE TITLE
Click on note leads to note opening [feature request][UX]

### ISSUE THREAD

**Issue by alltheseas** [darashi/searchnos#1]
## User Story
As a nos.today user who is searching for information on a particular topic, I would like to be able to click on a note AND nos.today to open that noteID immediately, so that I can investigate the context of the note among adjacent notes.

### Acceptance Criteria
1. Nos.today user can click on a note in the search results
2. If nos.today user clicks on a note in the search results, this opens that note in a Nostr client
3. If nos.today user is on desktop browser, open iris.to messenger in new tab directly to the noteID (iris.to/noteID123)
4. If nos.today user on a mobile device, open the default Nostr messenger or give option for user to select Nostr client of choice (e.g. Damus on iOS, Amethyst on Android etc.)

**Comment by alltheseas** [comment]
On iPhone, tapping on the note author brings me to their npub, and *not* the relevant noteID.

This is what happens when I click on a note in iPad browser:

![nos today error click](https://user-images.githubusercontent.com/64376233/229171421-372c148c-2039-4782-bb69-90a330d0edae.png)

**Comment by darashi** [comment]
Thanks for sharing. I think I understand your use case.

Actually, the time display is a NIP-21 link to the note. Could you please try it? It is difficult to find out, so I think it would be better to use a different representation. (When the time is within 1 minute, this link text was not showing up, so I made it always show up.)

I am aware that this link does not work well in many environments because it is not a normal link but in a NIP-21 compliant scheme. However, I did this intentionally to avoid linking to certain clients.

I'm not an expert in browser extensions, but is it possible to solve this by, for example, using a browser extension to hook the NIP-21 URL and redirect each user to their favorite client? If possible, that seems to be the best way.

Although, it seems difficult to use a browser extension on an iPad. I guess you could install the native Nostr client app on the iPad to open it, though. 

Or maybe it would be more realistic to add a function to copy the note Bech32 to avoid linking to a specific client.

**Comment by alltheseas** [comment]
-tapping profile picture opens npub link
-tapping name opens npub link
-tapping @ id opens npub
-tapping time opens note
-tapping in negative space does nothing 
-tapping on non-hyperlink note text does nothing 
-tapping on hyperlink in note text opens hyperlink

https://user-images.githubusercontent.com/64376233/229205412-8473c114-36f5-45b6-b3c3-3515ccb3b403.MOV

**Comment by darashi** [comment]
I have changed the color of the links to make it easier to see that they are clickable. I will continue to explore other improvements that can be made.

And since this repository is for relay implementation searchnos, I have set up a separate repository https://github.com/darashi/nos.today for nos.today web UI. I would be happy if you could help me with the nos.today UI there. Let me close this issue.
